### ISSUE TITLE
An impolite issue

### ISSUE THREAD

**Issue by bb7133** [bb7133/pingcap-newbie-workshop#2]
Please check [this doc](https://docs.google.com/document/d/1J1nwAs8aC8gjFqoPMWSGI9Iemh23mslah_XUMxHtTbs/edit) for more details.

**Comment by niubell** [comment]
Hi, [this doc](https://docs.google.com/document/d/1J1nwAs8aC8gjFqoPMWSGI9Iemh23mslah_XUMxHtTbs/edit) is not available for me, PTAL @bb7133

**Comment by lzrkid** [comment]
maybe a private doc？

**Comment by bb7133** [comment]
Sorry that I made a mistake, thank you very much for your reviews. @niubell @lzrkid
